-- Ausgabenkategorien (Rottöne)
UPDATE categories SET color = '#FF0000' WHERE id = 1;  -- A: Haushalt (Rot)
UPDATE categories SET color = '#FF3333' WHERE id = 2;  -- A: Unterhaltung (Helleres Rot)
UPDATE categories SET color = '#CC0000' WHERE id = 3;  -- A: Haus (Dunkleres Rot)
UPDATE categories SET color = '#FF6666' WHERE id = 4;  -- A: Kontoführung (Sehr helles Rot)
UPDATE categories SET color = '#990000' WHERE id = 5;  -- A: Versicherung (Sehr dunkles Rot)
UPDATE categories SET color = '#FF9999' WHERE id = 6;  -- A: Diverses (Pastellrot)
UPDATE categories SET color = '#CC3333' WHERE id = 7;  -- A: KFZ (Mittleres Rot)
UPDATE categories SET color = '#FF5500' WHERE id = 8;  -- A: Telefon/Internet (Rotorange)
UPDATE categories SET color = '#CC6666' WHERE id = 9;  -- A: Friseur (Gedämpftes Rot)
UPDATE categories SET color = '#FF0066' WHERE id = 10; -- A: Kleidung (Magentarot)
UPDATE categories SET color = '#CC0033' WHERE id = 11; -- A: Medien (Kirschrot)
UPDATE categories SET color = '#990033' WHERE id = 12; -- A: (Hör)Buch (Weinrot)
UPDATE categories SET color = '#FF3300' WHERE id = 13; -- A: Urlaub (Orangerot)
UPDATE categories SET color = '#CC3300' WHERE id = 14; -- A: Elektrogerät (Ziegelrot)
UPDATE categories SET color = '#FF6633' WHERE id = 15; -- A: Freizeit (Korallenrot)
UPDATE categories SET color = '#993333' WHERE id = 16; -- A: Geschenk (Rostrot)
UPDATE categories SET color = '#FF0033' WHERE id = 17; -- A: Gesundheit (Erdbeerrot)
UPDATE categories SET color = '#CC6633' WHERE id = 18; -- A: Betriebskosten (Terrakotta)
UPDATE categories SET color = '#FF9966' WHERE id = 19; -- A: Zinsen (Lachsrot)
UPDATE categories SET color = '#CC9999' WHERE id = 20; -- A: Kinder (Altrosa)

-- Einnahmenkategorien (Grüntöne)
UPDATE categories SET color = '#00CC00' WHERE id = 21; -- E: opta data Gruppe (Mittleres Grün)
UPDATE categories SET color = '#009900' WHERE id = 22; -- E: HTBLA (Dunkelgrün)
UPDATE categories SET color = '#00FF66' WHERE id = 23; -- E: Zinsen (Mintgrün)
UPDATE categories SET color = '#33CC33' WHERE id = 24; -- E: Sonstige (Grasgrün)
UPDATE categories SET color = '#006633' WHERE id = 25; -- E: Vermietung (Tannengrün)
UPDATE categories SET color = '#66FF66' WHERE id = 26; -- A: Ansparen (Hellgrün) 